version: '3'
services:
  db:
    image: mysql:5.7
    container_name: 'db'
    environment:                  
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: django-db
      MYSQL_USER: django
      MYSQL_PASSWORD: django
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
  
  web:
    build: .
    volumes: 
      - .:/src
    ports:
      - "8000:8000"
    container_name: 'web'
    depends_on:               
      - db
    links:
      - selenium
    command: python works/manage.py runserver 0.0.0.0:8000

  selenium:
    image: selenium/standalone-chrome:4.0.0-beta-1-prerelease-20201208
    container_name: 'selenium'
    ports:
      - 4444:4444
